import 'models.dart';

const Map<int, String> surahArabicNames = {
  1: 'الفاتحة',
  2: 'البقرة',
  3: 'آل عمران',
  4: 'النساء',
  5: 'المائدة',
  6: 'الأنعام',
  7: 'الأعراف',
  8: 'الأنفال',
  9: 'التوبة',
  10: 'يونس',
  11: 'هود',
  12: 'يوسف',
  13: 'الرعد',
  14: 'ابراهيم',
  15: 'الحجر',
  16: 'النحل',
  17: 'الإسراء',
  18: 'الكهف',
  19: 'مريم',
  20: 'طه',
  21: 'الأنبياء',
  22: 'الحج',
  23: 'المؤمنون',
  24: 'النور',
  25: 'الفرقان',
  26: 'الشعراء',
  27: 'النمل',
  28: 'القصص',
  29: 'العنكبوت',
  30: 'الروم',
  31: 'لقمان',
  32: 'السجدة',
  33: 'الأحزاب',
  34: 'سبإ',
  35: 'فاطر',
  36: 'يس',
  37: 'الصافات',
  38: 'ص',
  39: 'الزمر',
  40: 'غافر',
  41: 'فصلت',
  42: 'الشورى',
  43: 'الزخرف',
  44: 'الدخان',
  45: 'الجاثية',
  46: 'الأحقاف',
  47: 'محمد',
  48: 'الفتح',
  49: 'الحجرات',
  50: 'ق',
  51: 'الذاريات',
  52: 'الطور',
  53: 'النجم',
  54: 'القمر',
  55: 'الرحمن',
  56: 'الواقعة',
  57: 'الحديد',
  58: 'المجادلة',
  59: 'الحشر',
  60: 'الممتحنة',
  61: 'الصف',
  62: 'الجمعة',
  63: 'المنافقون',
  64: 'التغابن',
  65: 'الطلاق',
  66: 'التحريم',
  67: 'الملك',
  68: 'القلم',
  69: 'الحاقة',
  70: 'المعارج',
  71: 'نوح',
  72: 'الجن',
  73: 'المزمل',
  74: 'المدثر',
  75: 'القيامة',
  76: 'الانسان',
  77: 'المرسلات',
  78: 'النبإ',
  79: 'النازعات',
  80: 'عبس',
  81: 'التكوير',
  82: 'الإنفطار',
  83: 'المطففين',
  84: 'الإنشقاق',
  85: 'البروج',
  86: 'الطارق',
  87: 'الأعلى',
  88: 'الغاشية',
  89: 'الفجر',
  90: 'البلد',
  91: 'الشمس',
  92: 'الليل',
  93: 'الضحى',
  94: 'الشرح',
  95: 'التين',
  96: 'العلق',
  97: 'القدر',
  98: 'البينة',
  99: 'الزلزلة',
  100: 'العاديات',
  101: 'القارعة',
  102: 'التكاثر',
  103: 'العصر',
  104: 'الهمزة',
  105: 'الفيل',
  106: 'قريش',
  107: 'الماعون',
  108: 'الكوثر',
  109: 'الكافرون',
  110: 'النصر',
  111: 'المسد',
  112: 'الإخلاص',
  113: 'الفلق',
  114: 'الناس',
};

const Map<int, SurahSeed> surahSeeds = {
  1: SurahSeed(englishName: 'The Opening', chronologicalOrder: 5),
  2: SurahSeed(englishName: 'The Cow', chronologicalOrder: 87),
  3: SurahSeed(englishName: 'The Family of Imraan', chronologicalOrder: 89),
  4: SurahSeed(englishName: 'The Women', chronologicalOrder: 92),
  5: SurahSeed(englishName: 'The Table', chronologicalOrder: 113),
  6: SurahSeed(englishName: 'The Cattle', chronologicalOrder: 55),
  7: SurahSeed(englishName: 'The Heights', chronologicalOrder: 39),
  8: SurahSeed(englishName: 'The Spoils of War', chronologicalOrder: 88),
  9: SurahSeed(englishName: 'The Repentance', chronologicalOrder: 112),
  10: SurahSeed(englishName: 'Jonas', chronologicalOrder: 51),
  11: SurahSeed(englishName: 'Hud', chronologicalOrder: 52),
  12: SurahSeed(englishName: 'Joseph', chronologicalOrder: 53),
  13: SurahSeed(englishName: 'The Thunder', chronologicalOrder: 96),
  14: SurahSeed(englishName: 'Abraham', chronologicalOrder: 72),
  15: SurahSeed(englishName: 'The Rock', chronologicalOrder: 54),
  16: SurahSeed(englishName: 'The Bee', chronologicalOrder: 70),
  17: SurahSeed(englishName: 'The Night Journey', chronologicalOrder: 50),
  18: SurahSeed(englishName: 'The Cave', chronologicalOrder: 69),
  19: SurahSeed(englishName: 'Mary', chronologicalOrder: 44),
  20: SurahSeed(englishName: 'Taa-Haa', chronologicalOrder: 45),
  21: SurahSeed(englishName: 'The Prophets', chronologicalOrder: 73),
  22: SurahSeed(englishName: 'The Pilgrimage', chronologicalOrder: 103),
  23: SurahSeed(englishName: 'The Believers', chronologicalOrder: 74),
  24: SurahSeed(englishName: 'The Light', chronologicalOrder: 102),
  25: SurahSeed(englishName: 'The Criterion', chronologicalOrder: 42),
  26: SurahSeed(englishName: 'The Poets', chronologicalOrder: 47),
  27: SurahSeed(englishName: 'The Ant', chronologicalOrder: 48),
  28: SurahSeed(englishName: 'The Stories', chronologicalOrder: 49),
  29: SurahSeed(englishName: 'The Spider', chronologicalOrder: 85),
  30: SurahSeed(englishName: 'The Romans', chronologicalOrder: 84),
  31: SurahSeed(englishName: 'Luqman', chronologicalOrder: 57),
  32: SurahSeed(englishName: 'The Prostration', chronologicalOrder: 75),
  33: SurahSeed(englishName: 'The Clans', chronologicalOrder: 90),
  34: SurahSeed(englishName: 'Sheba', chronologicalOrder: 58),
  35: SurahSeed(englishName: 'The Originator', chronologicalOrder: 43),
  36: SurahSeed(englishName: 'Yaseen', chronologicalOrder: 41),
  37: SurahSeed(englishName: 'Those drawn up in Ranks', chronologicalOrder: 56),
  38: SurahSeed(englishName: 'The letter Saad', chronologicalOrder: 38),
  39: SurahSeed(englishName: 'The Groups', chronologicalOrder: 59),
  40: SurahSeed(englishName: 'The Forgiver', chronologicalOrder: 60),
  41: SurahSeed(englishName: 'Explained in detail', chronologicalOrder: 61),
  42: SurahSeed(englishName: 'Consultation', chronologicalOrder: 62),
  43: SurahSeed(englishName: 'Ornaments of gold', chronologicalOrder: 63),
  44: SurahSeed(englishName: 'The Smoke', chronologicalOrder: 64),
  45: SurahSeed(englishName: 'Crouching', chronologicalOrder: 65),
  46: SurahSeed(englishName: 'The Dunes', chronologicalOrder: 66),
  47: SurahSeed(englishName: 'Muhammad', chronologicalOrder: 95),
  48: SurahSeed(englishName: 'The Victory', chronologicalOrder: 111),
  49: SurahSeed(englishName: 'The Inner Apartments', chronologicalOrder: 106),
  50: SurahSeed(englishName: 'The letter Qaaf', chronologicalOrder: 34),
  51: SurahSeed(englishName: 'The Winnowing Winds', chronologicalOrder: 67),
  52: SurahSeed(englishName: 'The Mount', chronologicalOrder: 76),
  53: SurahSeed(englishName: 'The Star', chronologicalOrder: 23),
  54: SurahSeed(englishName: 'The Moon', chronologicalOrder: 37),
  55: SurahSeed(englishName: 'The Beneficent', chronologicalOrder: 97),
  56: SurahSeed(englishName: 'The Inevitable', chronologicalOrder: 46),
  57: SurahSeed(englishName: 'The Iron', chronologicalOrder: 94),
  58: SurahSeed(englishName: 'The Pleading Woman', chronologicalOrder: 105),
  59: SurahSeed(englishName: 'The Exile', chronologicalOrder: 101),
  60: SurahSeed(
      englishName: 'She that is to be examined', chronologicalOrder: 91),
  61: SurahSeed(englishName: 'The Ranks', chronologicalOrder: 109),
  62: SurahSeed(englishName: 'Friday', chronologicalOrder: 110),
  63: SurahSeed(englishName: 'The Hypocrites', chronologicalOrder: 104),
  64: SurahSeed(englishName: 'Mutual Disillusion', chronologicalOrder: 108),
  65: SurahSeed(englishName: 'Divorce', chronologicalOrder: 99),
  66: SurahSeed(englishName: 'The Prohibition', chronologicalOrder: 107),
  67: SurahSeed(englishName: 'The Sovereignty', chronologicalOrder: 77),
  68: SurahSeed(englishName: 'The Pen', chronologicalOrder: 2),
  69: SurahSeed(englishName: 'The Reality', chronologicalOrder: 78),
  70: SurahSeed(englishName: 'The Ascending Stairways', chronologicalOrder: 79),
  71: SurahSeed(englishName: 'Noah', chronologicalOrder: 71),
  72: SurahSeed(englishName: 'The Jinn', chronologicalOrder: 40),
  73: SurahSeed(englishName: 'The Enshrouded One', chronologicalOrder: 3),
  74: SurahSeed(englishName: 'The Cloaked One', chronologicalOrder: 4),
  75: SurahSeed(englishName: 'The Resurrection', chronologicalOrder: 31),
  76: SurahSeed(englishName: 'Man', chronologicalOrder: 98),
  77: SurahSeed(englishName: 'The Emissaries', chronologicalOrder: 33),
  78: SurahSeed(englishName: 'The Announcement', chronologicalOrder: 80),
  79: SurahSeed(englishName: 'Those who drag forth', chronologicalOrder: 81),
  80: SurahSeed(englishName: 'He frowned', chronologicalOrder: 24),
  81: SurahSeed(englishName: 'The Overthrowing', chronologicalOrder: 7),
  82: SurahSeed(englishName: 'The Cleaving', chronologicalOrder: 82),
  83: SurahSeed(englishName: 'Defrauding', chronologicalOrder: 86),
  84: SurahSeed(englishName: 'The Splitting Open', chronologicalOrder: 83),
  85: SurahSeed(englishName: 'The Constellations', chronologicalOrder: 27),
  86: SurahSeed(englishName: 'The Morning Star', chronologicalOrder: 36),
  87: SurahSeed(englishName: 'The Most High', chronologicalOrder: 8),
  88: SurahSeed(englishName: 'The Overwhelming', chronologicalOrder: 68),
  89: SurahSeed(englishName: 'The Dawn', chronologicalOrder: 10),
  90: SurahSeed(englishName: 'The City', chronologicalOrder: 35),
  91: SurahSeed(englishName: 'The Sun', chronologicalOrder: 26),
  92: SurahSeed(englishName: 'The Night', chronologicalOrder: 9),
  93: SurahSeed(englishName: 'The Morning Hours', chronologicalOrder: 11),
  94: SurahSeed(englishName: 'The Consolation', chronologicalOrder: 12),
  95: SurahSeed(englishName: 'The Fig', chronologicalOrder: 28),
  96: SurahSeed(englishName: 'The Clot', chronologicalOrder: 1),
  97: SurahSeed(englishName: 'The Power, Fate', chronologicalOrder: 25),
  98: SurahSeed(englishName: 'The Evidence', chronologicalOrder: 100),
  99: SurahSeed(englishName: 'The Earthquake', chronologicalOrder: 93),
  100: SurahSeed(englishName: 'The Chargers', chronologicalOrder: 14),
  101: SurahSeed(englishName: 'The Calamity', chronologicalOrder: 30),
  102: SurahSeed(englishName: 'Competition', chronologicalOrder: 16),
  103: SurahSeed(
      englishName: 'The Declining Day, Epoch', chronologicalOrder: 13),
  104: SurahSeed(englishName: 'The Traducer', chronologicalOrder: 32),
  105: SurahSeed(englishName: 'The Elephant', chronologicalOrder: 19),
  106: SurahSeed(englishName: 'Quraysh', chronologicalOrder: 29),
  107: SurahSeed(englishName: 'Almsgiving', chronologicalOrder: 17),
  108: SurahSeed(englishName: 'Abundance', chronologicalOrder: 15),
  109: SurahSeed(englishName: 'The Disbelievers', chronologicalOrder: 18),
  110: SurahSeed(englishName: 'Divine Support', chronologicalOrder: 114),
  111: SurahSeed(englishName: 'The Palm Fibre', chronologicalOrder: 6),
  112: SurahSeed(englishName: 'Sincerity', chronologicalOrder: 22),
  113: SurahSeed(englishName: 'The Dawn', chronologicalOrder: 20),
  114: SurahSeed(englishName: 'Mankind', chronologicalOrder: 21),
};
